In [ ]:
print("Road Accident Prediction")

Road Accident Prediction

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv("/content/accident_prediction_india.csv")

In [ ]:
df.head(5)

,State Name,City Name,Year,Month,Day of Week,Time of Day,Accident Severity,Number of Vehicles Involved,Vehicle Type Involved,Number of Casualties,...,Road Type,Road Condition,Lighting Conditions,Traffic Control Presence,Speed Limit (km/h),Driver Age,Driver Gender,Driver License Status,Alcohol Involvement,Accident Location Details
0,Jammu and Kashmir,Unknown,2021,May,Monday,1:46,Serious,5,Cycle,0,...,National Highway,Wet,Dark,Signs,61,66,Male,NaN,Yes,Curve
1,Uttar Pradesh,Lucknow,2018,January,Wednesday,21:30,Minor,5,Truck,5,...,Urban Road,Dry,Dusk,Signs,92,60,Male,NaN,Yes,Straight Road
2,Chhattisgarh,Unknown,2023,May,Wednesday,5:37,Minor,5,Pedestrian,6,...,National Highway,Under Construction,Dawn,Signs,120,26,Female,NaN,No,Bridge
3,Uttar Pradesh,Lucknow,2020,June,Saturday,0:31,Minor,3,Bus,10,...,State Highway,Dry,Dark,Signals,76,34,Female,Valid,Yes,Straight Road
4,Sikkim,Unknown,2021,August,Thursday,11:21,Minor,5,Cycle,7,...,Urban Road,Wet,Dusk,Signs,115,30,Male,NaN,No,Intersection

In [ ]:
df.shape

(3000, 22)

In [ ]:
df.isnull().sum()

State Name                       0
City Name                        0
Year                             0
Month                            0
Day of Week                      0
Time of Day                      0
Accident Severity                0
Number of Vehicles Involved      0
Vehicle Type Involved            0
Number of Casualties             0
Number of Fatalities             0
Weather Conditions               0
Road Type                        0
Road Condition                   0
Lighting Conditions              0
Traffic Control Presence       716
Speed Limit (km/h)               0
Driver Age                       0
Driver Gender                    0
Driver License Status          975
Alcohol Involvement              0
Accident Location Details        0
dtype: int64

In [ ]:
df.dropna(inplace=True)
df['Accident Severity'].unique()

array(['Minor', 'Serious', 'Fatal'], dtype=object)

In [ ]:
df=df[df['Accident Severity'] != "Fatal"]
df['Accident Severity'] = df['Accident Severity'].str.strip()
df['Accident Severity']=df['Accident Severity'].map({
    'Minor':0, 'Serious':1
})

In [ ]:
df.head(5)

,State Name,City Name,Year,Month,Day of Week,Time of Day,Accident Severity,Number of Vehicles Involved,Vehicle Type Involved,Number of Casualties,...,Road Type,Road Condition,Lighting Conditions,Traffic Control Presence,Speed Limit (km/h),Driver Age,Driver Gender,Driver License Status,Alcohol Involvement,Accident Location Details
3,Uttar Pradesh,Lucknow,2020,June,Saturday,0:31,0,3,Bus,10,...,State Highway,Dry,Dark,Signals,76,34,Female,Valid,Yes,Straight Road
5,Meghalaya,Unknown,2020,November,Tuesday,8:4,1,1,Truck,6,...,Village Road,Dry,Daylight,Police Checkpost,48,44,Male,Expired,Yes,Bridge
7,Himachal Pradesh,Unknown,2022,December,Wednesday,11:40,0,3,Truck,1,...,State Highway,Damaged,Dark,Police Checkpost,62,42,Female,Valid,No,Curve
13,Bihar,Unknown,2020,June,Wednesday,6:47,1,5,Car,0,...,State Highway,Wet,Dusk,Signals,98,44,Female,Valid,No,Bridge
14,Telangana,Unknown,2021,August,Friday,18:57,1,3,Bus,6,...,National Highway,Wet,Dawn,Police Checkpost,47,54,Male,Valid,No,Intersection

In [ ]:
df_new=df[[
    'Number of Vehicles Involved',
    'Number of Casualties',
    'Speed Limit (km/h)',
    	'Driver Age',
   	'Alcohol Involvement',
    'Accident Severity'

]].copy()
df_new['Alcohol Involvement']=df_new['Alcohol Involvement'].map({
    'Yes':1, 'No':0
})

In [ ]:

x=df_new.iloc[:,:-1]
y=df_new.iloc[:,-1]

In [ ]:
x

,Number of Vehicles Involved,Number of Casualties,Speed Limit (km/h),Driver Age,Alcohol Involvement
3,3,10,76,34,1
5,1,6,48,44,1
7,3,1,62,42,0
13,5,0,98,44,0
14,3,6,47,54,0
...,...,...,...,...,...
2989,4,4,72,58,0
2990,5,6,99,60,1
2992,5,3,33,58,1
2995,5,4,74,43,1
2997,2,8,47,57,1

In [ ]:
y

3       0
5       1
7       0
13      1
14      1
       ..
2989    0
2990    1
2992    0
2995    0
2997    0
Name: Accident Severity, Length: 1031, dtype: int64

In [ ]:
df.shape

(1031, 22)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
classifier = LogisticRegression()

In [ ]:
classifier.fit(X_train,y_train)

LogisticRegression()

In [ ]:
y_pred=classifier.predict(X_test)

In [ ]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score,classification_report

In [ ]:
print(accuracy_score(y_pred,y_test))

0.5542635658914729

In [ ]:
print(classification_report(y_pred , y_test))

              precision    recall  f1-score   support

           0       0.72      0.53      0.61       171
           1       0.39      0.60      0.47        87

    accuracy                           0.55       258
   macro avg       0.56      0.56      0.54       258
weighted avg       0.61      0.55      0.57       258